### PR TITLE
various css improvements

### PR DESCRIPTION
**Pull request by voxain**
your structure is a mess, man.

### CODE REVIEW

**Comment by itzTheMeow** [comment]
the corners here need fixed, they are square:
image

**Review by itzTheMeow — CHANGES_REQUESTED** [review]
The corners here are square:
image
They should be rounded :wink:

Other than that, looks good

**Comment by voxain** [comment]
The corners are rounded in the CSS, however the edges looking square is from the blur effect not working correctly with rounded corners (yet). The same applies for the taskbar menu.
The only ways to fix this would be to either remove the rounded corners or the blur effect, which I didn't want neither of it to be removed.

**Comment by itzTheMeow** [comment]
well it will have to be fixed somehow :eyes:

**Comment by voxain** [comment]
What's your suggestion then? I can't fix the jaggy corners since it's a chromium bug, but what do you want it to look like?

**Comment by itzTheMeow** [comment]
How it looks right now is fine, just the corners need fixed (somehow).
I'll merge this for now, and when there is a fix, make another PR.

**Pull request merged**
